on: push
name: Validate
jobs:
  fixup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ianwremmel/prevent-fixup-commits@master
  nopush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ianwremmel/prevent-nopush-commits@master
