on: push
name: Validate
jobs:
  fixup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: self
      uses: ./
  nopush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ianwremmel/prevent-nopush-commits@master
